### ISSUE TITLE
No module named _multiprocessing

### ISSUE THREAD

**Issue by schrink** [McSwindler/kodi-mirror#1]
Hi, 

I have installed your plugin on OSX, Kodi 16 Beta. It installs but when I try to open it I get the following error. Any idea? 

20:57:50 T:123145304526848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--No module named _multiprocessing
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: 
                                            Traceback (most recent call last):
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/addon.py", line 17, in <module>
                                                import serverSettings
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/serverSettings.py", line 5, in <module>
                                                from multiprocessing import Pool
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/multiprocessing/__init__.py", line 83, in <module>
                                            ImportError: No module named _multiprocessing
                                            -->End of Python script error report<--
20:57:50 T:140735251742720   ERROR: GetDirectory - Error getting plugin://plugin.video.mirror/
20:57:50 T:140735251742720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mirror/) failed
20:57:50 T:123145308282880  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
20:58:56 T:123145325989888 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)

**Comment by McSwindler** [comment]
I don't have a Mac to test with, but it looks like the problematic import isn't used anymore, so hopefully just removing it will work.

You can download the updated here: https://github.com/McSwindler/kodi-mirror/blob/master/dist/plugin.video.mirror.zip?raw=true

Let me know how it works for you :)

**Comment by schrink** [comment]
Hey, thanks a lot! It works now, I can install it and configure. But it get's stuck on "Opening stream" forever. This is from the error log: 

02:49:29 T:123145328214016   ERROR: EXCEPTION: XBMC is not playing any media file
02:49:29 T:123145328214016   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/threading.py", line 484, in run
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/RPCSocket.py", line 49, in _wait
                                                self._callbacks[js['method']](self, js)
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/MirrorPlayer.py", line 61, in _onPause
                                                if self.isPaused():
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/MirrorPlayer.py", line 132, in isPaused
                                                start_time = self.getTime()
                                            RuntimeError: XBMC is not playing any media file
02:49:29 T:123145326067712 WARNING: CPythonInvoker(19, /Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/addon.py): the python script "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE
02:49:29 T:140735163060224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mirror/?mode=server&id=007a0be4bdd68c25f0db4b964e997ca1]
02:49:42 T:123145304526848 WARNING: CSkinInfo: failed to load skin settings
02:49:42 T:140735163060224   ERROR: Control 1100 in window 13000 has been asked to focus, but it can't
02:49:47 T:123145326604288 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
02:50:07 T:123145305063424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('id',)
                                            Traceback (most recent call last):
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/addon.py", line 111, in <module>
                                                startMirror(_getParam('id'))
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/addon.py", line 96, in startMirror
                                                listitem = player.playFromServer()
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/MirrorPlayer.py", line 89, in playFromServer
                                                current = self._getItem()
                                              File "/Users/vladimirlelicanin/Library/Application Support/Kodi/addons/plugin.video.mirror/MirrorPlayer.py", line 191, in _getItem
                                                id = d['result']['item']['id']
                                            KeyError: ('id',)
                                            -->End of Python script error report<--
02:50:07 T:123145307746304  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
02:51:12 T:123145330360320 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)

**Comment by McSwindler** [comment]
Can you try it now? 
I made some tweaks, though I'm not 100% sure if it'll solve everything. If there are further errors could you  turn on debug logging and post any messages prepended with 'kodi-mirror::' as well as what type of file you are playing on the server Kodi instance. (like if it's an internet stream, something in your library, or a DVD, etc)
